LICENSE
Missing LICENSE file is added for this repo.
The added LICENSE is same as django-ipam.
Fixes #5
=> [LICENSE] Added LICENSE #5

.travis.yml, requirements.txt, runcheckmigration
GCI task: https://codein.withgoogle.com/dashboard/task-instances/4887920570793984/
=> [ci] add ci check for migrations

requirements.txt
=> [requirements] Depend only on django-ipam

README.rst
Added requires.io badge in README
=> [requirements] Requires.io Badge

.travis.yml, openwisp_ipam/tests/tests.py, requirements-test.txt, requirements.txt, setup.py
=> [deps] Support for Python 3.6, 3.7, Django 3.0 and update dependencies

.gitignore, README.rst
=> [docs/minor] Documentation improvements #38

.travis.yml, openwisp_ipam/api/views.py, requirements.txt, run-qa-checks, runtests.py, setup.cfg, setup.py
Updated dependencies and minor cleanup.
=> Updated dependencies and minor cleanup

openwisp_ipam/migrations/0001_initial.py, setup.cfg, tests/openwisp2/sample_ipam/migrations/0001_initial.py, tests/openwisp2/sample_ipam/migrations/0002_remove_ipaddress_organization.py
=> [migration] Swapper migrations changes #48

openwisp_ipam/api/__init__.py, openwisp_ipam/urls.py, tests/openwisp2/urls.py
=> [change] Refactor URLs to use path()

openwisp_ipam/tests/test_users_integration.py, tests/openwisp2/sample_ipam/tests.py
Fixed integration tests with openwisp-users 0.4.1
=> [fix] Fixed integration tests with openwisp-users 0.4.1

README.rst, openwisp_ipam/admin.py, openwisp_ipam/templates/admin/openwisp-ipam/subnet/change_list.html, requirements.txt, tests/openwisp2/settings.py
Added the support of `django-reversion`.
Fixes #57
=> [feat] Added django-reversion support #57

openwisp_ipam/api/views.py, openwisp_ipam/tests/test_api.py
=> [fix] Fix exception in api #71

openwisp_ipam/migrations/0005_default_groups_permissions.py, openwisp_ipam/migrations/__init__.py, openwisp_ipam/tests/test_admin.py, tests/openwisp2/sample_ipam/migrations/0004_default_groups_permissions.py
=> [feature] Created default permissions for the default groups #55

openwisp_ipam/api/views.py
Tests are failing because of a change in https://github.com/openwisp/openwisp-users/pull/230
This PR will fix it.
=> [qa] Fix permission classes in API

.github/workflows/ci.yml
Fixed CI
relate to https://github.com/openwisp/openwisp-controller/issues/417
=> [ci] Fixed CI for django~=3.0.0

openwisp_ipam/apps.py, openwisp_ipam/tests/test_admin.py, requirements-test.txt, requirements.txt, tests/openwisp2/settings.py
Registered menu groups
closes #108
=> [enhancement] Registered menu groups #108

openwisp_ipam/tests/test_admin.py, openwisp_ipam/tests/test_multitenant.py, tests/openwisp2/settings.py
Modified tests of import_subnet and menu_items.
Fixes #112
=> [fix] Failing tests fixed #112

openwisp_ipam/admin.py, openwisp_ipam/base/models.py, openwisp_ipam/compat.py, openwisp_ipam/migrations/0002_remove_ipaddress_organization.py, openwisp_ipam/migrations/0004_subnet_organization_unique_together.py, openwisp_ipam/tests/__init__.py, openwisp_ipam/tests/test_admin.py, openwisp_ipam/tests/test_api.py, openwisp_ipam/tests/test_models.py, openwisp_ipam/tests/test_multitenant.py, requirements.txt, tests/openwisp2/sample_ipam/migrations/0003_fix_multitenancy.py, tests/openwisp2/sample_users/migrations/0001_initial.py, tests/openwisp2/sample_users/models.py, tests/openwisp2/settings.py
Removing swapper dependency so that whatever is required will be consumed by `openwisp-utils`.
Closes #125
=> [deps] Removing swapper dependency #125

openwisp_ipam/tests/test_multitenant.py
=> [change] Updated tests to use administrator for failing tests #135

openwisp_ipam/api/views.py
=> [fix] Fixed API docs errror #128

README.rst, openwisp_ipam/admin.py, openwisp_ipam/filters.py, requirements-test.txt, requirements.txt, tests/openwisp2/settings.py
=> [feature] Added autocomplete filters

openwisp_ipam/api/views.py, requirements.txt
Depends on :
- https://github.com/openwisp/openwisp-users/pull/338
=> [chores] Used openwisp-users `ProtectedAPIMixin`

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, .github/pull_request_template.md
=> [feature] Added the issue and PR template

.github/workflows/pypi.yml, requirements-test.txt, requirements.txt, tests/openwisp2/sample_users/migrations/0001_initial.py, tests/openwisp2/settings.py
Bumped openwisp-utils[rest]~=1.1.0
=> [ci] Added workflow for publishing on PyPI

requirements-test.txt, requirements.txt
- Bumped openwisp-users~=1.1.0
- Bumped openwisp-utils~=1.1.1
=> [deps] Upgraded openwisp-users and openwisp-utils

CHANGES.rst, openwisp_ipam/__init__.py
=> 1.1.0 release

.github/workflows/version-branch.yml, CHANGES.rst, openwisp_ipam/__init__.py, requirements-test.txt, requirements.txt
=> [ci] Added GitHub workflow to replicate commits to version branch

.github/workflows/ci.yml, tests/openwisp2/sample_users/migrations/0001_initial.py
Closes #184
Added:
- Support for Django >=5.1,<5.3
- Support for Python >=3.12, 3.14
Removed:
- Support for Python < 3.9
- Support for Django < 4.2
=> [deps] Add support for Django >=5.1,<5.3 and Python >=3.12, 3.14 #184
