openwisp/openwisp-ipam

- openwisp_ipam/tests.py
- tests/settings.py
- tests/urls.py
This code effectively adds a test corresponding to this error(issue #7) and includes allauth urls to solve the problem.
Fixes #7
> [urls] creating a new user gave NoReverseMatch (solves #7)

- openwisp_ipam/admin.py
- openwisp_ipam/tests.py
Implements multitenancy in admin and adds a test for the same. 
and thereby Fixes #6
> [admin] implement multitenant admin

- .travis.yml
- openwisp_ipam/models.py
- requirements-test.txt
- requirements.txt
- runflake8
- runisort
- setup.cfg
Clean isort and flake. Added commit message check in travis.
Fixes #13
Fixes #14
> [qa] Cleanup isort and flake8 settings in an OpenWISP module #13

- .travis.yml
- openwisp_ipam/admin.py
- requirements-test.txt
- requirements.txt
- runcheckmigration
Update requirements and fix import issues because openwisp-utils 0.3 now move the multitenancy feature to openwisp-users 0.1.11. Also change travis script to run common CI and remove unnecessary script.
> [ci] Update openwisp-utils and migrate to common CI script

- openwisp_ipam/urls.py
Related to issue #24
This adds support for urls.py update in django-ipam.
Prior to it:
The exact traceback in Travis was: 
```
File "/home/travis/virtualenv/python3.6.10/src/django-ipam/django_ipam/tests/base/test_api.py", line 199, in test_hosts_list_api
response = self.client.get(reverse('ipam:hosts', args=(subnet.id,)))
File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/django/urls/base.py", line 90, in reverse
return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
File "/home/travis/virtualenv/python3.6.10/lib/python3.6/site-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'hosts' not found. 'hosts' is not a valid view function or pattern name. …
```
> [subnet-visualizer] Adding support for updated urls in django-ipam

- README.rst
Like the images are not showing in PyPi, these URLs will have the same problem, so I changed them to absolute URLs.
> [docs] Using absolute path for links

- README.rst
Changed the URL for the images in the rest api section to load all the
images correctly in README.
Fixes #67
> [docs] Fixed image rendering on README #67

- openwisp_ipam/static/openwisp-ipam/css/admin.css
- openwisp_ipam/static/openwisp-ipam/js/subnet.js
- openwisp_ipam/templates/admin/openwisp-ipam/subnet/change_form.html
- openwisp_ipam/tests/test_admin.py
> [feature] Go to IP

- openwisp_ipam/static/openwisp-ipam/js/subnet.js
- openwisp_ipam/templates/admin/openwisp-ipam/subnet/change_form.html
This is slightly different than the solution proposed in the issue discussions but I hope this one works out better :smile:
Closes #39
> [admin] Add "goto" in subnet

- openwisp_ipam/apps.py
- openwisp_ipam/tests/test_admin.py
- requirements-test.txt
- requirements.txt
- tests/openwisp2/settings.py
Added menu items (openwisp-utils menu) for Subnet and IpAdress models.
This is WIP PR which requires the new version release of openwisp-utils.
Fixes #37
> [admin] Added menu items #37

- README.rst
- openwisp_ipam/api/views.py
- openwisp_ipam/apps.py
> [api] Added Scoped Throttling #34

- .gitignore
- openwisp_ipam/api/serializers.py
- openwisp_ipam/api/utils.py
- openwisp_ipam/api/views.py
- openwisp_ipam/base/models.py
- openwisp_ipam/tests/test_multitenant.py
- requirements.txt
> [api] Implement multitenancy in API #61

- openwisp_ipam/base/models.py
- openwisp_ipam/tests/test_models.py
> [fix] Fix overlapping shared/non-shared subnet validation #88

- openwisp_ipam/admin.py
- openwisp_ipam/base/models.py
- openwisp_ipam/tests/test_models.py
> [feature] Allow shared subnets to have non shared child subnets #90

- .github/workflows/ci.yml
- openwisp_ipam/base/models.py
- openwisp_ipam/tests/test_models.py
- requirements.txt
> [Fix] Exlcuded child subnets from overlapping validation #87

- openwisp_ipam/api/views.py
- openwisp_ipam/tests/test_admin.py
- openwisp_ipam/tests/test_api.py
- Fixed `subnet /32` pie chart.
Fixes #129
See comment https://github.com/openwisp/openwisp-ipam/issues/129#issuecomment-1048060911
> [fix] Fixed subnet /32 & /128 pie chart error #129

- openwisp_ipam/base/models.py
- openwisp_ipam/migrations/0001_initial.py
- openwisp_ipam/tests/__init__.py
- openwisp_ipam/tests/test_api.py
- openwisp_ipam/tests/test_models.py
- openwisp_ipam/tests/test_multitenant.py
- tests/openwisp2/sample_ipam/migrations/0001_initial.py
- Updated the **name field** of the `Subnet` model to not be blank.
- Updated `__str__` of `AbstractSubnet` model.
- Updated `test_multitenancy_subnet_queryset`, `test_create_subnet_api`.
- Added `test_save_none_subnet_fails`, `test_save_blank_subnet_fails`.
- Removed redundant `test_subnet_string_representation`.
Fixes #131
> [fix] Fixed creation of subnet without name #131

- openwisp_ipam/admin.py
- openwisp_ipam/tests/test_admin.py
Bug:
Accessing admin change view of a non-existent subnet object
resulted in Server Error 500 because the "DoesNotExist"
conditioned was not handled.
> [fix] Added error handling in Subnet admin change view

- .github/workflows/ci.yml
- README.rst
- openwisp_ipam/__init__.py
- openwisp_ipam/apps.py
- openwisp_ipam/base/models.py
- requirements-test.txt
- requirements.txt
- tests/openwisp2/sample_ipam/__init__.py
- tests/openwisp2/sample_ipam/apps.py
- tests/openwisp2/sample_users/__init__.py
- tests/openwisp2/sample_users/apps.py
- Dropped support for Python 3.7
- Dropped support for Django 4.0
- Bumped openpyxl~=3.1.2
> [deps] Added support for Django 4.1.0 and Django 4.2.0 

- docs/developer/installation.rst
Closes #170 
Recommend using [Python Virtualenv](https://virtualenv.pypa.io/en/latest/) in development instructions.
> [docs] Added instruction for using virtualenv

- openwisp_ipam/base/models.py
- openwisp_ipam/tests/test_models.py
Added validation to restrict creating an IPv4 subnet under an IPv6 master subnet. Now, the UI displays an appropriate error message instead of a server error.
Fixes #154
Closes #154
Created a new validation check for version mismatch and previously there was a test case for checking the internal server error, so updated that test case to check the validation error.
> [fix] Prevent IPv4 subnet creation from IPv6 master subnet #154
